---
version: '3.5'
services:
  zookeeper2:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker2:
    image: confluentinc/cp-kafka:7.2.1
    container_name: broker2
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper2:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092,PLAINTEXT_INTERNAL://broker2:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-bridge:
    image: strimzi/kafka-bridge:0.19.0
    entrypoint: /opt/strimzi/bin/kafka_bridge_run.sh
    command: --config-file=config/application.properties
    volumes:
      - ./application.properties:/opt/strimzi/config/application.properties
    depends_on:
      - broker2
    ports:
      - 9080:8080

